merkle_root = ""                                                  # @dev - Merkle Root, which is consist of both a job_title_commitment and a _skills_combined_commitment
#merkle_root_of_job_title_commitment_merkle_tree = ""             # @dev - Merkle Root of the job title commitment tree.
#merkle_root_of_skill_commitments_merkle_tree = ["", "", "", ""]  # @dev - Merkle Root of the skill commitment tree.

hash_path = ["", ""]

#index = ""
#index_of_job_title_commitment_merkle_tree = ""                   # @dev - Position in the tree.
#index_of_skill_commitments_merkle_tree = ["", "", "", ""]        # @dev - Position in the tree.

secret = ""       # @dev - A hidden metadata hash (private)
nullifier = ""    # @dev - Should be a Poseidon2 Hash

[job_career_and_skill_data]
job_title_hash = "";                    # @dev - Hash of the job title (e.g. Hashed "Software Engineer").
skill_hashes = ["", "", "", ""]         # @dev - List of skill hashes (e.g. Hashed ["Rust", "ZK", "React"]).
job_title_commitment = ""               # @dev - Commitment Hash of the job title
skills_combined_commitment = ""         # @dev - Commitment Hash of the skills-combined
#skill_commitments = ["", "", "", ""]    # @dev - Commitment Hashes of the revealed skills.